### ISSUE TITLE
Unable to run on MAC/Linux

### ISSUE THREAD

**Issue by SleepingDragon969** [RebelKeithy/Metallurgy3#1]
The game crashes due the directory source file being wrong. The Linux and MAC systems use the slash " / ". PCs use backslash " \ ". When we try to run the game it crashes right off the back because it cannot find the proper directory. Here is the crash report.

---- Minecraft Crash Report ----
// On the bright side, I bought you a teddy bear!

Time: 3/20/13 2:31 PM
Description: Failed to start game

java.lang.NullPointerException
    at rebelkeithy.mods.metallurgy.machines.MetallurgyMachines.initMint(MetallurgyMachines.java:188)
    at rebelkeithy.mods.metallurgy.machines.MetallurgyMachines.preInit(MetallurgyMachines.java:122)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
    at java.lang.reflect.Method.invoke(Method.java:597)
    at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:515)
    at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
    at java.lang.reflect.Method.invoke(Method.java:597)
    at com.google.common.eventbus.EventHandler.handleEvent(EventHandler.java:74)
    at com.google.common.eventbus.SynchronizedEventHandler.handleEvent(SynchronizedEventHandler.java:45)
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:314)
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:296)
    at com.google.common.eventbus.EventBus.post(EventBus.java:267)
    at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:165)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
    at java.lang.reflect.Method.invoke(Method.java:597)
    at com.google.common.eventbus.EventHandler.handleEvent(EventHandler.java:74)
    at com.google.common.eventbus.SynchronizedEventHandler.handleEvent(SynchronizedEventHandler.java:45)
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:314)
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:296)
    at com.google.common.eventbus.EventBus.post(EventBus.java:267)
    at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:98)
    at cpw.mods.fml.common.Loader.loadMods(Loader.java:505)
    at cpw.mods.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:160)
    at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:406)
    at net.minecraft.client.MinecraftAppletImpl.func_71384_a(SourceFile:56)
    at net.minecraft.client.Minecraft.run(Minecraft.java:728)
    at java.lang.Thread.run(Thread.java:680)
## A detailed walkthrough of the error, its code path and all known details is as follows:

-- System Details --
Details:
    Minecraft Version: 1.5
    Operating System: Mac OS X (x86_64) version 10.6.8
    Java Version: 1.6.0_43, Apple Inc.
    Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Apple Inc.
    Memory: 1004620744 bytes (958 MB) / 1071579136 bytes (1021 MB) up to 2675638272 bytes (2551 MB)
    JVM Flags: 3 total; -Xbootclasspath/a:/System/Library/PrivateFrameworks/JavaApplicationLauncher.framework/Resources/LauncherSupport.jar -Xms1024M -Xmx2560M
    AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
    Suspicious classes: FML and Forge are installed
    IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
    FML: MCP v7.42 FML v5.0.25.589 Minecraft Forge 7.7.0.589 19 mods loaded, 19 mods active
    mcp [Minecraft Coder Pack](minecraft.jar) Unloaded->Constructed->Pre-initialized
    FML [Forge Mod Loader](coremods) Unloaded->Constructed->Pre-initialized
    Forge [Minecraft Forge](coremods) Unloaded->Constructed->Pre-initialized
    mod_TooManyItems [mod_TooManyItems](minecraft.jar) Unloaded->Constructed->Pre-initialized
    HarkenScythe_Core [HarkenScythe](1.5HarkenScythe_v2.0.1Forgenew.zip) Unloaded->Constructed->Pre-initialized
    BattleTowers [Battle Towers](BattleTowers_1.5.zip) Unloaded->Constructed->Pre-initialized
    eplus [Enchanting Plus](EnchantingPlus-1.13.2.jar) Unloaded->Constructed->Pre-initialized
    Ideas [Ideas](Metallurgy) Unloaded->Constructed->Pre-initialized
    Metallurgy3Core [Metallurgy 3 Core](Metallurgy) Unloaded->Constructed->Pre-initialized
    Metallurgy3Base [Metallurgy 3 Base](Metallurgy) Unloaded->Constructed->Pre-initialized
    Metallurgy3Machines [Metallurgy 3 Machines](Metallurgy) Unloaded->Constructed->Errored
    Metallurgy3Vanilla [Metallurgy 3 Vanilla](Metallurgy) Unloaded->Constructed->Pre-initialized
    teeluk_SpecialArmor [SpecialArmor](SpecialArmor_1.5anew.zip) Unloaded->Constructed->Pre-initialized
    AS_UpdateCheck [AtomicStryker Update Check Mod](UpdateCheckerMod_1.5.zip) Unloaded->Constructed->Pre-initialized
    UpgradePlus [Upgrade Plus](UpgradePlus-15.zip) Unloaded->Constructed->Pre-initialized
    mod_ZanMinimap [mod_ZanMinimap](ZansMinimap1.5.zip) Unloaded->Constructed->Pre-initialized
    Backpack [Backpack](backpack-1.7.8-1.5.zip) Unloaded->Constructed->Pre-initialized
    diamondbuckets [Diamond Buckets 0.96](diamondbuckets_v096.zip) Unloaded->Constructed->Pre-initialized
    IronChest [Iron Chest](ironchest-universal-1.5-5.2.1.288.zip) Unloaded->Constructed->Pre-initialized
    LWJGL: 2.4.2
    OpenGL: ATI Radeon HD 4670 OpenGL Engine GL version 2.1 ATI-1.6.36, ATI Technologies Inc.
    Is Modded: Definitely; Client brand changed to 'forge,fml'
    Type: Client (map_client.txt)
    Texture Pack: Default
    Profiler Position: N/A (disabled)
    Vec3 Pool Size: ~~ERROR~~ NullPointerException: null

**Comment by SleepingDragon969** [comment]
At least I believe this is the problem. Please check and let me know

**Comment by RebelKeithy** [comment]
I believe I've fixed the problem, check my twitter for the update.
