### ISSUE TITLE
Crashed on multiplayer test startup.

### ISSUE THREAD

**Issue by Huminax** [RebelKeithy/Metallurgy3#17]
Very recent download of minecraft_server.jar
Minecraft Forge verson: 7.7.0.608
Metallurgy version: 3.0.0.0.5

---- Minecraft Crash Report ----
// Ouch. That hurt :(

Time: 3/25/13 10:03 PM
Description: Exception in server tick loop

cpw.mods.fml.common.LoaderException: java.lang.NoClassDefFoundError: rebelkeithy/mods/metallurgy/machines/crusher/GuiCrusher
    at cpw.mods.fml.common.LoadController.transition(LoadController.java:142)
    at cpw.mods.fml.common.Loader.loadMods(Loader.java:514)
    at cpw.mods.fml.server.FMLServerHandler.beginServerLoading(FMLServerHandler.java:85)
    at cpw.mods.fml.common.FMLCommonHandler.onServerStart(FMLCommonHandler.java:352)
    at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:69)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:429)
    at net.minecraft.server.ThreadMinecraftServer.run(SourceFile:573)
Caused by: java.lang.NoClassDefFoundError: rebelkeithy/mods/metallurgy/machines/crusher/GuiCrusher
    at rebelkeithy.mods.metallurgy.machines.MetallurgyMachines.initCrusher(MetallurgyMachines.java:292)
    at rebelkeithy.mods.metallurgy.machines.MetallurgyMachines.preInit(MetallurgyMachines.java:118)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:515)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at com.google.common.eventbus.EventHandler.handleEvent(EventHandler.java:74)
    at com.google.common.eventbus.SynchronizedEventHandler.handleEvent(SynchronizedEventHandler.java:45)
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:314)
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:296)
    at com.google.common.eventbus.EventBus.post(EventBus.java:267)
    at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:165)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at com.google.common.eventbus.EventHandler.handleEvent(EventHandler.java:74)
    at com.google.common.eventbus.SynchronizedEventHandler.handleEvent(SynchronizedEventHandler.java:45)
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:314)
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:296)
    at com.google.common.eventbus.EventBus.post(EventBus.java:267)
    at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:98)
    at cpw.mods.fml.common.Loader.loadMods(Loader.java:513)
    ... 5 more
Caused by: java.lang.ClassNotFoundException: rebelkeithy.mods.metallurgy.machines.crusher.GuiCrusher
    at cpw.mods.fml.relauncher.RelaunchClassLoader.findClass(RelaunchClassLoader.java:211)
    at java.lang.ClassLoader.loadClass(Unknown Source)
    at java.lang.ClassLoader.loadClass(Unknown Source)
    ... 33 more
Caused by: java.lang.NoClassDefFoundError: net/minecraft/client/gui/inventory/GuiContainer
    at java.lang.ClassLoader.defineClass1(Native Method)
    at java.lang.ClassLoader.defineClass(Unknown Source)
    at java.security.SecureClassLoader.defineClass(Unknown Source)
    at cpw.mods.fml.relauncher.RelaunchClassLoader.findClass(RelaunchClassLoader.java:200)
    ... 35 more
Caused by: java.lang.ClassNotFoundException: net.minecraft.client.gui.inventory.GuiContainer
    at cpw.mods.fml.relauncher.RelaunchClassLoader.findClass(RelaunchClassLoader.java:211)
    at java.lang.ClassLoader.loadClass(Unknown Source)
    at java.lang.ClassLoader.loadClass(Unknown Source)
    ... 39 more
Caused by: java.lang.NullPointerException
    at cpw.mods.fml.relauncher.RelaunchClassLoader.findClass(RelaunchClassLoader.java:200)
    ... 41 more
## A detailed walkthrough of the error, its code path and all known details is as follows:

-- System Details --
Details:
    Minecraft Version: 1.5.1
    Operating System: Windows 7 (amd64) version 6.1
    Java Version: 1.7.0_17, Oracle Corporation
    Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
    Memory: 4053698816 bytes (3865 MB) / 4116054016 bytes (3925 MB) up to 4116054016 bytes (3925 MB)
    JVM Flags: 2 total; -Xmx4096M -Xms4096M
    AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
    Suspicious classes: FML and Forge are installed
    IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
    FML: MCP v7.44 FML v5.1.8.608 Minecraft Forge 7.7.0.608 8 mods loaded, 8 mods active
    mcp [Minecraft Coder Pack](minecraft.jar) Unloaded->Constructed->Pre-initialized
    FML [Forge Mod Loader](coremods) Unloaded->Constructed->Pre-initialized
    Forge [Minecraft Forge](coremods) Unloaded->Constructed->Pre-initialized
    Ideas [Ideas](Metallurgy 3.0.0.0.5.jar) Unloaded->Constructed->Pre-initialized
    Metallurgy3Core [Metallurgy 3 Core](Metallurgy 3.0.0.0.5.jar) Unloaded->Constructed->Pre-initialized
    Metallurgy3Base [Metallurgy 3 Base](Metallurgy 3.0.0.0.5.jar) Unloaded->Constructed->Pre-initialized
    Metallurgy3Machines [Metallurgy 3 Machines](Metallurgy 3.0.0.0.5.jar) Unloaded->Constructed->Errored
    Metallurgy3Vanilla [Metallurgy 3 Vanilla](Metallurgy 3.0.0.0.5.jar) Unloaded->Constructed->Pre-initialized
    Profiler Position: N/A (disabled)
    Is Modded: Definitely; Server brand changed to 'fml'
    Type: Dedicated Server (map_server.txt)

**Comment by Wolverine903** [comment]
http://pastebin.com/WfBXtEk3

I get the same error I think, I posted my error log in the link above.

**Comment by RebelKeithy** [comment]
This particular error should be fixed in the next update, if you still crash please open a new issue
