### ISSUE TITLE
Minecraft Crash on Startup due to Machines Error

### ISSUE THREAD

**Issue by SleepingDragon969** [RebelKeithy/Metallurgy3#28]
I installed the new Metallurgy 3...7 and the game crashes upon start up. Here is the report.

---- Minecraft Crash Report ----
// This is a token for 1 free hug. Redeem at your nearest Mojangsta: [~~HUG~~]

Time: 3/28/13 8:50 AM
Description: Failed to start game

java.lang.NullPointerException
    at rebelkeithy.mods.metallurgy.machines.MetallurgyMachines.initMint(MetallurgyMachines.java:188)
    at rebelkeithy.mods.metallurgy.machines.MetallurgyMachines.preInit(MetallurgyMachines.java:121)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
    at java.lang.reflect.Method.invoke(Method.java:597)
    at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:515)
    at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
    at java.lang.reflect.Method.invoke(Method.java:597)
    at com.google.common.eventbus.EventHandler.handleEvent(EventHandler.java:74)
    at com.google.common.eventbus.SynchronizedEventHandler.handleEvent(SynchronizedEventHandler.java:45)
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:314)
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:296)
    at com.google.common.eventbus.EventBus.post(EventBus.java:267)
    at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:165)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
    at java.lang.reflect.Method.invoke(Method.java:597)
    at com.google.common.eventbus.EventHandler.handleEvent(EventHandler.java:74)
    at com.google.common.eventbus.SynchronizedEventHandler.handleEvent(SynchronizedEventHandler.java:45)
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:314)
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:296)
    at com.google.common.eventbus.EventBus.post(EventBus.java:267)
    at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:98)
    at cpw.mods.fml.common.Loader.loadMods(Loader.java:513)
    at cpw.mods.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:160)
    at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:407)
    at net.minecraft.client.MinecraftAppletImpl.func_71384_a(SourceFile:56)
    at net.minecraft.client.Minecraft.run(Minecraft.java:729)
    at java.lang.Thread.run(Thread.java:680)
## A detailed walkthrough of the error, its code path and all known details is as follows:

-- System Details --
Details:
    Minecraft Version: 1.5.1
    Operating System: Mac OS X (x86_64) version 10.6.8
    Java Version: 1.6.0_43, Apple Inc.
    Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Apple Inc.
    Memory: 1004888768 bytes (958 MB) / 1071579136 bytes (1021 MB) up to 3212509184 bytes (3063 MB)
    JVM Flags: 3 total; -Xbootclasspath/a:/System/Library/PrivateFrameworks/JavaApplicationLauncher.framework/Resources/LauncherSupport.jar -Xms1024M -Xmx3072M
    AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
    Suspicious classes: FML and Forge are installed
    IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
    FML: MCP v7.44 FML v5.1.8.608 Minecraft Forge 7.7.0.608 18 mods loaded, 18 mods active
    mcp [Minecraft Coder Pack](minecraft.jar) Unloaded->Constructed->Pre-initialized
    FML [Forge Mod Loader](coremods) Unloaded->Constructed->Pre-initialized
    Forge [Minecraft Forge](coremods) Unloaded->Constructed->Pre-initialized
    mod_TooManyItems [mod_TooManyItems](minecraft.jar) Unloaded->Constructed->Pre-initialized
    AsgardShield_Core [AsgardShield](1.5.1AsgardShield_Core_v1.0.5Forge.zip) Unloaded->Constructed->Pre-initialized
    ASAddon_Hallowed [AS Addon- Hallowed](1.5.1ASAddon_Hallowed_1.0.3Forge.zip) Unloaded->Constructed->Pre-initialized
    ASAddon_NetherEnder [AS Addon- Nether-Ender](1.5.1ASAddon_NetherEnder_1.0.3Forge.zip) Unloaded->Constructed->Pre-initialized
    HarkenScythe_Core [HarkenScythe](1.5.1HarkenScythe_v2.0.2Forge.zip) Unloaded->Constructed->Pre-initialized
    eplus [Enchanting Plus](EnchantingPlus-1.5.1-1.14.3.jar) Unloaded->Constructed->Pre-initialized
    Ideas [Ideas](Metallurgy 3.0.0.0.7.jar) Unloaded->Constructed->Pre-initialized
    Metallurgy3Core [Metallurgy 3 Core](Metallurgy 3.0.0.0.7.jar) Unloaded->Constructed->Pre-initialized
    Metallurgy3Base [Metallurgy 3 Base](Metallurgy 3.0.0.0.7.jar) Unloaded->Constructed->Pre-initialized
    Metallurgy3Machines [Metallurgy 3 Machines](Metallurgy 3.0.0.0.7.jar) Unloaded->Constructed->Errored
    Metallurgy3Vanilla [Metallurgy 3 Vanilla](Metallurgy 3.0.0.0.7.jar) Unloaded->Constructed->Pre-initialized
    teeluk_SpecialArmor [SpecialArmor](SpecialArmor_1.5.1atp.zip) Unloaded->Constructed->Pre-initialized
    mod_ZanMinimap [mod_ZanMinimap](ZansMinimap1.5.1.zip) Unloaded->Constructed->Pre-initialized
    IronChest [Iron Chest](ironchest-universal-1.5.1-tp.zip) Unloaded->Constructed->Pre-initialized
    TwilightForest [The Twilight Forest](twilightforest-1.17.0tp.zip) Unloaded->Constructed->Pre-initialized
    LWJGL: 2.4.2
    OpenGL: ATI Radeon HD 4670 OpenGL Engine GL version 2.1 ATI-1.6.36, ATI Technologies Inc.
    Is Modded: Definitely; Client brand changed to 'forge,fml'
    Type: Client (map_client.txt)
    Texture Pack: converted-Sphax PureBDcraft  64x MC15
    Profiler Position: N/A (disabled)
    Vec3 Pool Size: ~~ERROR~~ NullPointerException: null

**Comment by Wolverine903** [comment]
Yes I get this same error for single player as well.  Both single and multiplayer seem to have the same error in regards to the Metallurgy3Machines.

**Comment by RebelKeithy** [comment]
Fixed 3.0.0.0.7.1
