### ISSUE TITLE
Expects Jar without version in name

### ISSUE THREAD

**Issue by Vyrebird** [RebelKeithy/Metallurgy3#3]
If the Metallurgy jar is left at the default name (eg "Metallurgy3.0.0.0.1.jar"), Minecraft crashes on load.  The console indicates the mod is looking only for "Metallurgy.jar" - renaming the jar to that fixes the issue.
(Win 7, if it's relevant)

The relevant snippet of the console output seems to be:

2013-03-20 19:33:59 [INFO] [STDOUT] [Metallurgy3] Successfully created/read configuration file for Metallurgy 3 Core
2013-03-20 19:33:59 [INFO] [STDOUT] reading sets 1
2013-03-20 19:33:59 [INFO] [STDERR] java.io.FileNotFoundException: .....minecraft\mods\Metallurgy.jar (The system cannot find the file specified)
2013-03-20 19:33:59 [INFO] [STDERR]     at java.util.zip.ZipFile.open(Native Method)
2013-03-20 19:33:59 [INFO] [STDERR]     at java.util.zip.ZipFile.<init>(Unknown Source)
2013-03-20 19:33:59 [INFO] [STDERR]     at java.util.zip.ZipFile.<init>(Unknown Source)
2013-03-20 19:33:59 [INFO] [STDERR]     at java.util.zip.ZipFile.<init>(Unknown Source)
2013-03-20 19:33:59 [INFO] [STDERR]     at rebelkeithy.mods.metallurgy.core.MetalInfoDatabase.readMetalDataFromJar(MetalInfoDatabase.java:146)
2013-03-20 19:33:59 [INFO] [STDERR]     at rebelkeithy.mods.metallurgy.metals.MetallurgyMetals.preInit(MetallurgyMetals.java:111)

**Comment by RebelKeithy** [comment]
Fixed in update
