### ISSUE TITLE
Attacking Mobs With Amordrine Sword Causes NPE

### ISSUE THREAD

**Issue by ddelaparte** [RebelKeithy/Metallurgy3#42]
Title says it all - Error is as follows:
java.lang.NullPointerException
    at rebelkeithy.mods.metallurgy.metals.NetherSwordHitListener.hitEntity(NetherSwordHitListener.java:80)
    at rebelkeithy.mods.metallurgy.core.metalsets.ItemMetallurgySword.func_77644_a(ItemMetallurgySword.java:31)
    at net.minecraft.item.ItemStack.func_77961_a(ItemStack.java:362)
    at net.minecraft.entity.player.EntityPlayer.func_71059_n(EntityPlayer.java:1662)
    at net.minecraft.client.multiplayer.PlayerControllerMP.func_78764_a(PlayerControllerMP.java:455)
    at net.minecraft.client.Minecraft.func_71402_c(Minecraft.java:1288)
    at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1791)
    at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:831)
    at net.minecraft.client.Minecraft.run(Minecraft.java:756)
    at java.lang.Thread.run(Unknown Source)

**Comment by RebelKeithy** [comment]
Fixed
