### ISSUE TITLE
Can't open Mint Storage.

### ISSUE THREAD

**Issue by Wolftein** [RebelKeithy/Metallurgy3#54]
2013-04-22 23:43:35 [SEVERE] java.lang.reflect.InvocationTargetException
2013-04-22 23:43:35 [SEVERE]    at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
2013-04-22 23:43:35 [SEVERE]    at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
2013-04-22 23:43:35 [SEVERE]    at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
2013-04-22 23:43:35 [SEVERE]    at java.lang.reflect.Constructor.newInstance(Constructor.java:525)
2013-04-22 23:43:35 [SEVERE]    at rebelkeithy.mods.guiregistry.GuiRegistry.getServerGuiElement(GuiRegistry.java:60)
2013-04-22 23:43:35 [SEVERE]    at cpw.mods.fml.common.network.NetworkRegistry.openRemoteGui(NetworkRegistry.java:357)
2013-04-22 23:43:35 [SEVERE]    at cpw.mods.fml.common.network.FMLNetworkHandler.openGui(FMLNetworkHandler.java:351)
2013-04-22 23:43:35 [SEVERE]    at net.minecraft.entity.player.EntityPlayer.openGui(EntityPlayer.java:2410)
2013-04-22 23:43:35 [SEVERE]    at rebelkeithy.mods.guiregistry.GuiRegistry.openGui(GuiRegistry.java:51)
2013-04-22 23:43:35 [SEVERE]    at rebelkeithy.mods.metallurgy.machines.mint.BlockMintStorage.func_71903_a(BlockMintStorage.java:168)
2013-04-22 23:43:35 [SEVERE]    at net.minecraft.item.ItemInWorldManager.func_73078_a(ItemInWorldManager.java:575)
2013-04-22 23:43:35 [SEVERE]    at net.minecraft.network.NetServerHandler.func_72472_a(NetServerHandler.java:869)
2013-04-22 23:43:35 [SEVERE]    at net.minecraft.network.packet.Packet15Place.func_73279_a(Unknown Source)
2013-04-22 23:43:35 [SEVERE]    at org.spigotmc.netty.NettyNetworkManager.func_74428_b(NettyNetworkManager.java:189)
2013-04-22 23:43:35 [SEVERE]    at net.minecraft.network.NetServerHandler.func_72570_d(NetServerHandler.java:213)
2013-04-22 23:43:35 [SEVERE]    at net.minecraft.network.NetworkListenThread.func_71747_b(Unknown Source)
2013-04-22 23:43:35 [SEVERE]    at org.spigotmc.netty.NettyServerConnection.func_71747_b(NettyServerConnection.java:68)
2013-04-22 23:43:35 [SEVERE]    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:968)
2013-04-22 23:43:35 [SEVERE]    at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:323)
2013-04-22 23:43:35 [SEVERE]    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:836)
2013-04-22 23:43:35 [SEVERE]    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:720)
2013-04-22 23:43:35 [SEVERE]    at net.minecraft.server.ThreadMinecraftServer.run(Unknown Source)
2013-04-22 23:43:35 [SEVERE] Caused by: java.lang.AbstractMethodError: rebelkeithy.mods.metallurgy.machines.mint.TileEntityMintStorage.func_70295_k_()V
2013-04-22 23:43:35 [SEVERE]    at rebelkeithy.mods.metallurgy.machines.mint.ContainerMintStorage.<init>(ContainerMintStorage.java:22)
2013-04-22 23:43:35 [SEVERE]    ... 22 more

**Comment by Wolverine903** [comment]
Are you using the latest version of Metallurgy?  I can open the Mint Storage with no issues.

**Comment by Wolftein** [comment]
I'm using build "Metallurgy 3.0.0.0.9.2" + MCPC Lastest build.

**Comment by Wolverine903** [comment]
Well there is a 3.0.0.0.9.3.  So maybe try that one.

**Comment by Wolftein** [comment]
Already tried it, same exception.

**Comment by RebelKeithy** [comment]
It seems to be an update to forge that broke it, if it still happens next update reopen the issue.
